default:
  image: maven:3.8.5-openjdk-17
  cache:
    paths:
      - .m2/repository
      - target/

variables:
#  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_CLI_OPTS: " --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build
  - test
  - benchmark

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS install
  artifacts:
    paths:
      - target/feign-dsl-json-1.0-SNAPSHOT.jar

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify

benchmark:
  stage: benchmark
  dependencies:
    - build
  script:
    - cd mb
    - mvn clean install
#  run benchmark
    - java -cp ./target/feign-dsl-json-mb-1.0-SNAPSHOT.jar eu.pm.feign.decoderBenchmark -rf json
#  create chart with results
    - java -cp ./target/feign-dsl-json-mb-1.0-SNAPSHOT.jar eu.pm.feign.resultsChart
    - mkdir benchmark
    - cp jmh-result.png benchmark/jmh-result-decoders.png
    - cp jmh-result.json benchmark/jmh-result-decoders.json
    - cd benchmark
#      git add -uv ./jmh-result.png
#      git add -uv ./jmh-result.png
#      git reset -- target
    - |
      git config --global user.name ${BENCHRESULTS_GITHUB_ACTOR}
      git config --global user.email ${BENCHRESULTS_GITHUB_ACTOR}@users.noreply.github.com
      git clone https://${BENCHRESULTS_GITHUB_ACTOR}:${BENCHRESULTS_GITHUB_TOKEN}@github.com/silviuilie/feign-dsl-json-benchmarks.git
      mv jmh-result-decoders.png feign-dsl-json-benchmarks/jmh-result-decoders.png  
      mv jmh-result-decoders.json feign-dsl-json-benchmarks/jmh-result-decoders.json  
      cd feign-dsl-json-benchmarks
      git add jmh-result-decoders.png
      git add jmh-result-decoders.json
      git commit -m "benchmark(update) new numbers"
      git push origin main

