default:
  image: maven:3.8.5-openjdk-17
  cache:
    paths:
      - .m2/repository/
      - target/

variables:
#  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_CLI_OPTS: " --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - test
  - benchmark

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  artifacts:
    paths:
      - target/feign-dsl-json-1.0-SNAPSHOT.jar

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify

benchmark:
  stage: benchmark
  script:
    - cd mb
    - mvn clean install
    - java -jar -cp ../target/feign-dsl-json-1.0-SNAPSHOT.jar /target/feign-dsl-json-mb-1.0-SNAPSHOT.jar -rf json
    - ls *.json
