default:
  image: maven:3.8.5-openjdk-17
  cache:
    paths:
      - .m2/repository
      - target/

variables:
#  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_CLI_OPTS: " --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build
  - test
  - benchmark

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS install
  artifacts:
    paths:
      - target/feign-dsl-json-1.0-SNAPSHOT.jar

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify

benchmark:
  stage: benchmark
  dependencies:
    - build
  script:
    - find .m2/repository/eu -print
    - cd mb
    - mvn clean install
    - find ./target -print
    - java -jar -cp .m2/repository/eu/pm/feign-dsl-json/feign-dsl-json/1.0-SNAPSHOT/feign-dsl-json-1.0-SNAPSHOT.jar /target/feign-dsl-json-1.0-SNAPSHOT.jar -rf json
    - ls *.json
